### ISSUE TITLE
The Blog feed is not up-to-date

### ISSUE THREAD

**Issue by samoht** [ocamllabs/ocl-reporter#54]
The end-of-year report doesn't appear on http://www.cl.cam.ac.uk/projects/ocamllabs/blogs/index.html

**Comment by avsm** [comment]
Thats because its in news/

**Comment by avsm** [comment]
Manually synched blog.

**Comment by amirmc** [comment]
The page probably needs to be regenerated.

The OCL news feed is in the appropriate place [1] and the feed content contains the new post [1]

[1] https://github.com/ocamllabs/ocl-reporter/blob/master/lib/data_blog.txt (see line 3)
[2] http://www.cl.cam.ac.uk/projects/ocamllabs/news/atom.xml
